# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('courseName',)},
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='buildingName',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='endTime',
            field=models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시'), (8, '8교시'), (9, '9교시')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='profName',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='startTime',
            field=models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시'), (8, '8교시'), (9, '9교시')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], default=0),
        ),
    ]
