# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='공학수학', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Semester')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
