# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170805_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buildingName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(default='공학수학', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='profName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
