# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170805_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='roomName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='roomType',
            field=models.CharField(default='', max_length=30),
        ),
    ]
