# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20170805_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MyCourse',
        ),
    ]
