# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20170805_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('duration', models.CharField(default='00:00', max_length=100, verbose_name='Duration')),
                ('filename', models.CharField(default=None, max_length=255, verbose_name='Filename')),
                ('file', models.FileField(default=None, upload_to='', verbose_name='File')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(default='')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course__courseName',),
            },
        ),
    ]
