# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseClass',
            field=models.CharField(default='00', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='roomCode',
            field=models.CharField(default='99999', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.IntegerField(choices=[(0, '일'), (1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='endTime',
            field=models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시'), (8, '8교시'), (9, '9교시'), (99, '0교시')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='startTime',
            field=models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시'), (8, '8교시'), (9, '9교시'), (99, '0교시')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(2017, 17), (2016, 16)], default=2017),
        ),
    ]
