# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170805_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buildingName',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='profName',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='roomName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='roomType',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
