# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170805_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='record',
            name='title',
        ),
        migrations.RemoveField(
            model_name='record',
            name='url',
        ),
    ]
