# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170805_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(default=None, upload_to='templates/records/', verbose_name='File'),
        ),
    ]
